language: elixir
cache:
  directories:
    - priv/plts
otp_release:
  - 22.3
  - 23.0
elixir:
  - 1.10.2
  - 1.11.1
matrix:
  include:
    - elixir: 1.11.1
      otp_release: 23.0
      env:
        - TEST_PERSISTENT_TERM=true
notifications:
  recipients:
    - vincefoley@gmail.com
    - brwcodes@gmail.com
    - ben.wilson@cargosense.com
script:
  - mix format --check-formatted
  - MIX_ENV=test mix local.hex --force && MIX_ENV=test mix do deps.get, deps.compile
  - ./test.sh
  - mkdir -p priv/plts
  - MIX_ENV=test mix dialyzer
